# Generated by Django 3.2.6 on 2021-09-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=500)),
                ('name', models.CharField(blank=True, default='user0', max_length=200, null=True)),
                ('displayuser', models.ManyToManyField(blank=True, to='todo.TodoUser')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=200)),
                ('date', models.DateTimeField(default='2021-09-19 21:18')),
                ('donebool', models.BooleanField(default=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.todouser')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
