# Generated by Django 3.2.6 on 2021-08-24 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='donebool',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 14, 58, 11, 316742)),
        ),
    ]
