# Generated by Django 3.2.6 on 2021-08-24 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210824_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 24, 17, 29, 29, 235293), null=True),
        ),
    ]
