# Generated by Django 3.2.6 on 2021-08-24 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 24, 17, 33, 5, 851495), null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='donebool',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
    ]
