# Generated by Django 3.2.6 on 2021-08-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210824_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default='2021-08-26 17:28'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='donebool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
