# Generated by Django 3.2.6 on 2021-09-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20210826_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=500)),
                ('name', models.CharField(blank=True, default='user0', max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default='2021-09-04 23:46'),
        ),
        migrations.AddField(
            model_name='todo',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.todouser'),
        ),
    ]
