# Generated by Django 3.2.6 on 2021-09-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210904_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='todouser',
            name='displayuser',
            field=models.ManyToManyField(related_name='_todo_todouser_displayuser_+', to='todo.TodoUser'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default='2021-09-06 06:21'),
        ),
    ]
