# Generated by Django 3.2.6 on 2021-09-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20210906_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default='2021-09-06 06:27'),
        ),
    ]
