# Generated by Django 3.2.6 on 2021-09-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default='2021-09-06 06:40'),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='displayuser',
            field=models.ManyToManyField(blank=True, null=True, related_name='_todo_todouser_displayuser_+', to='todo.TodoUser'),
        ),
    ]
