# Generated by Django 3.2.6 on 2021-09-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20210906_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default='2021-09-06 06:41'),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='displayuser',
            field=models.ManyToManyField(blank=True, related_name='_todo_todouser_displayuser_+', to='todo.TodoUser'),
        ),
    ]
