# Generated by Django 3.2.6 on 2021-09-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20210906_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default='2021-09-07 16:18'),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='displayuser',
            field=models.ManyToManyField(blank=True, to='todo.TodoUser'),
        ),
    ]
